name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save SSH private key
      run: |
        echo "${{ secrets.DOCKER_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy files to EC2 using SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_EC2_HOST }}
        username: ubuntu                   # ✅ your actual EC2 username
        key_path: key.pem
        port: 22
        source: .
        target: /home/ubuntu/portfolio     # ✅ adjust this if your user home path is different
